site_name: SotaZK Labs docs
docs_dir: ./docs
site_description: This is the docs for people learning ZKPs
site_author: sota-zk-labs
repo_url: https://github.com/sota-zk-labs/zkp-documents
site_url: https://docs.sotazk.org/

theme:
  name: material
  custom_dir: overrides
  include_search_page: true
  font:
    text: Inter
    code: Source Code Pro
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: deep purple # Primary colors
      accent: deep purple # accent color
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple # Primary colors
      accent: deep purple # accent color
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dracula
      primary: deep purple # Primary colors
      accent: deep purple # accent color
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.integration
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.indexes
    #- navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.action.edit

validation:
  absolute_links: warn

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
#      block_tag: 'pre' # We wrap block math in `<pre>` to avoid issues with MkDocs minify HTML plugin: https://github.com/byrnereese/mkdocs-minify-plugin
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - meta
  - smarty
  - pymdownx.extra

exclude_docs: |
  english/*
  index.md

plugins:
  - search
  - mkdocs_pymdownx_material_extras
  - callouts

extra_javascript:
  - javascripts/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js
#  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js

#extra_css:
#  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css
